import { PipelineDeal, PipelineStage, SourcingChannel, DealTier, BusinessType, OutreachContact, OutreachType, OutreachStatus } from "./types";

export const INITIAL_PIPELINE_DEALS: PipelineDeal[] = [
  {
    id: "deal-1",
    businessName: "Apex Plumbing & HVAC",
    stage: PipelineStage.DUE_DILIGENCE,
    verdict: "PAUSE",
    score: 40,
    adjustedSDE: 265000,
    askingPrice: 480000,
    purchaseMultiple: 2.04,
    baseOFCF: 116000,
    closeDayDSCR: 5.60,
    notes: "Phase 1 environmental passed. Quality of Earnings (QofE) review scheduled next week.",
    createdAt: "2026-05-10T10:00:00Z",
    lastUpdated: "2026-06-01T15:30:00Z",
    dealInput: {
      businessName: "Apex Plumbing & HVAC",
      dealSequence: DealTier.DEAL_1,
      businessType: BusinessType.PHYSICAL_SERVICE,
      industry: "Plumbing & HVAC Services",
      businessState: "CA",
      yearsInOperation: 12,
      sourcingChannel: SourcingChannel.BIZBUYSELL,
      sdeTTM: 265000,
      revenueTTM: 900000,
      ttmNetProfit: 180000,
      ownerW2Comp: 75000,
      ownerBenefits: 25000,
      itemizedAddBacks: [{ label: "One-time lawsuit settlement", amount: 15000 }],
      maintenanceCapEx3YrAvg: 30000,
      askingPrice: 480000,
      sellerNotePercentage: 15,
      sellerNoteRate: 6,
      sellerNoteDuration: 10,
      sbaLoanAmount: 360000,
      sbaMonthlyDebtService: 3500,
      sbaInterestRate: 10.5,
      sbaTermYears: 10,
      revenueY1: 780000,
      revenueY2: 840000,
      revenueY3: 900000,
      sdeY1: 220000,
      sdeY2: 245000,
      sdeY3: 265000,
      customerConcentrationMaxPct: 0.08,
      hasCustomerOver10PctContracted: true,
      bankStatementsAvailable: true,
      taxReturnsAvailable: true,
      pnlAvailable: true,
      bankDepositsMatchPnl: true,
      bankDepositVariancePct: 0.02,
      sba7aEligible: "Yes",
      veteransAdvantageApplied: true,
      platformConcentrationMaxPct: 0,
      platformName: "",
      paymentProcessorIssue: false,
      sellerIdentityDependencePct: 0,
      ownerDependencePathway: "A",
      keyEmployeeRisk: false,
      keyEmployeeRetentionPlan: true,
      remoteManageable: true,
      operatorProxyIdentified: true,
      communicationAccessConfirmed: true,
      capitalConfirmed: true,
      noCompetingLOI: true,
      isEcommerceSubscription: false,
      ecommerceRecurringRevenuePct: 0,
      governmentRevenuePct: 0,
      arAgingReportAvailable: true,
      customerListAvailable: true,
      hasVagueAddBacks: false,
      maxEarnoutAmount: 50000,
      earnoutDurationMonths: 12,
      equityInjectionIsLiquid: true,
      sdePeakLast5Years: 265000,
      monthlyFixedOpCosts: 22000,
      workingCapitalReplenishmentAnnual: 5000,
      capexDeferredMoreThan2Years: false,
      undisclosedPaymentTermination: false,
      referralSourceDependency: false,
      hiddenConcentrationRisk: false,
      pathwayA_GMInPlace: true,
      pathwayA_GMAgreement: true,
      pathwayA_GMPnlHistory: true,
      pathwayB_OwnerReplaceCost: 45000,
      pathwayC_WrittenSOPs: true,
      pathwayC_IndependentExecution30Days: true,
      pathwayC_PostClose90DayPlan: true,
      ownerPerformsSalesAndOpsNoPlan: false,
      ownerControlsPayrollSchedulingNoPlan: false,
      keyEmployeeResponsibleFor20Pct: false,
      keyEmployeeAgreementExists: true,
      keyEmployeeBonusEscrowed: true,
      keyEmployeeWillingToStay: true,
      criticalEmployeeRefusesToStay: false,
      remoteFinancialOversightLess2Hrs: true,
      remoteBlackoutSurvival72Hrs: true,
      ownerMustSignPermitsOrLicense: false,
      ownerValueAddConfirmation: true,
      minimalSoftwareInUse: true,
      manualProcessesIn3CoreWorkflows: true,
      staffTimeReplaceableByAutomation: true,
      recurringModelAvailable: true,
      customerRetentionOver60PctNoContract: true,
      noServiceContractsOffered: true,
      noOnlineBookingOrPortal: true,
      noDigitalMarketingInfrastructure: true,
      laborCostsOver40Pct: false,
      pricingNotRaisedIn2Years: true,
      dealBriefAvailable: true,
      bankDepositSupportAvailable: true,
      orgChartAvailable: true,
      sopsAvailable: true,
      ninetyDayPlanAvailable: true,
      sellerIdentityEvidenceAvailable: true,
      platformConcentrationEvidenceAvailable: false,
      additionalDdDocsAvailable: true,
    }
  },
  {
    id: "deal-2",
    businessName: "CloudBytes SaaS",
    stage: PipelineStage.SCREENING,
    verdict: "PAUSE",
    score: 35,
    adjustedSDE: 290000,
    askingPrice: 900000,
    purchaseMultiple: 3.10,
    baseOFCF: 62000,
    closeDayDSCR: 1.62,
    notes: "Platform concentration is flagged. Analyzing customer retention trends.",
    createdAt: "2026-05-20T14:45:00Z",
    lastUpdated: "2026-05-31T09:15:00Z",
    dealInput: {
      businessName: "CloudBytes SaaS",
      dealSequence: DealTier.DEALS_2_5,
      businessType: BusinessType.SAAS_ADJACENT,
      industry: "B2B Software Development",
      businessState: "TX",
      yearsInOperation: 5,
      sourcingChannel: SourcingChannel.ACQUIRE,
      sdeTTM: 290000,
      revenueTTM: 650000,
      ttmNetProfit: 210000,
      ownerW2Comp: 60000,
      ownerBenefits: 20000,
      itemizedAddBacks: [],
      maintenanceCapEx3YrAvg: 0,
      askingPrice: 900000,
      sellerNotePercentage: 20,
      sellerNoteRate: 7,
      sellerNoteDuration: 5,
      sbaLoanAmount: 675000,
      sbaMonthlyDebtService: 7800,
      sbaInterestRate: 10.5,
      sbaTermYears: 10,
      revenueY1: 350000,
      revenueY2: 520000,
      revenueY3: 650000,
      sdeY1: 155000,
      sdeY2: 230000,
      sdeY3: 290000,
      customerConcentrationMaxPct: 0.12,
      hasCustomerOver10PctContracted: true,
      bankStatementsAvailable: true,
      taxReturnsAvailable: true,
      pnlAvailable: true,
      bankDepositsMatchPnl: true,
      bankDepositVariancePct: 0.01,
      sba7aEligible: "Yes",
      veteransAdvantageApplied: true,
      platformConcentrationMaxPct: 0.45,
      platformName: "AWS",
      paymentProcessorIssue: false,
      sellerIdentityDependencePct: 0.05,
      ownerDependencePathway: "C",
      keyEmployeeRisk: true,
      keyEmployeeRetentionPlan: false,
      remoteManageable: true,
      operatorProxyIdentified: true,
      communicationAccessConfirmed: true,
      capitalConfirmed: true,
      noCompetingLOI: true,
      isEcommerceSubscription: false,
      ecommerceRecurringRevenuePct: 0,
      governmentRevenuePct: 0,
      arAgingReportAvailable: true,
      customerListAvailable: true,
      hasVagueAddBacks: false,
      maxEarnoutAmount: 150000,
      earnoutDurationMonths: 18,
      equityInjectionIsLiquid: true,
      sdePeakLast5Years: 290000,
      monthlyFixedOpCosts: 15000,
      workingCapitalReplenishmentAnnual: 3000,
      capexDeferredMoreThan2Years: false,
      undisclosedPaymentTermination: false,
      referralSourceDependency: false,
      hiddenConcentrationRisk: false,
      pathwayA_GMInPlace: false,
      pathwayA_GMAgreement: false,
      pathwayA_GMPnlHistory: false,
      pathwayB_OwnerReplaceCost: 65000,
      pathwayC_WrittenSOPs: true,
      pathwayC_IndependentExecution30Days: true,
      pathwayC_PostClose90DayPlan: true,
      ownerPerformsSalesAndOpsNoPlan: false,
      ownerControlsPayrollSchedulingNoPlan: false,
      keyEmployeeResponsibleFor20Pct: true,
      keyEmployeeAgreementExists: true,
      keyEmployeeBonusEscrowed: true,
      keyEmployeeWillingToStay: true,
      criticalEmployeeRefusesToStay: false,
      remoteFinancialOversightLess2Hrs: true,
      remoteBlackoutSurvival72Hrs: true,
      ownerMustSignPermitsOrLicense: false,
      ownerValueAddConfirmation: false,
      minimalSoftwareInUse: false,
      manualProcessesIn3CoreWorkflows: true,
      staffTimeReplaceableByAutomation: true,
      recurringModelAvailable: true,
      customerRetentionOver60PctNoContract: true,
      noServiceContractsOffered: true,
      noOnlineBookingOrPortal: false,
      noDigitalMarketingInfrastructure: true,
      laborCostsOver40Pct: true,
      pricingNotRaisedIn2Years: false,
      dealBriefAvailable: true,
      bankDepositSupportAvailable: true,
      orgChartAvailable: true,
      sopsAvailable: true,
      ninetyDayPlanAvailable: true,
      sellerIdentityEvidenceAvailable: true,
      platformConcentrationEvidenceAvailable: true,
      additionalDdDocsAvailable: true,
    }
  },
  {
    id: "deal-3",
    businessName: "EcoPack Distributors",
    stage: PipelineStage.DEAL_INTAKE,
    verdict: "PASS",
    score: 28,
    adjustedSDE: 215000,
    askingPrice: 480000,
    purchaseMultiple: 2.23,
    baseOFCF: 85500,
    closeDayDSCR: 5.12,
    notes: "Off-market lead. Sourcing via direct owner outbound campaign.",
    createdAt: "2026-05-28T08:12:00Z",
    lastUpdated: "2026-06-01T11:00:00Z",
    dealInput: {
      businessName: "EcoPack Distributors",
      dealSequence: DealTier.DEAL_1,
      businessType: BusinessType.B2B_PROFESSIONAL,
      industry: "Packaging Distribution",
      businessState: "OH",
      yearsInOperation: 8,
      sourcingChannel: SourcingChannel.OFF_MARKET,
      sdeTTM: 215000,
      revenueTTM: 700000,
      ttmNetProfit: 145000,
      ownerW2Comp: 55000,
      ownerBenefits: 15000,
      itemizedAddBacks: [],
      maintenanceCapEx3YrAvg: 0,
      askingPrice: 480000,
      sellerNotePercentage: 15,
      sellerNoteRate: 6,
      sellerNoteDuration: 10,
      sbaLoanAmount: 360000,
      sbaMonthlyDebtService: 3500,
      sbaInterestRate: 10.5,
      sbaTermYears: 10,
      revenueY1: 620000,
      revenueY2: 670000,
      revenueY3: 700000,
      sdeY1: 180000,
      sdeY2: 200000,
      sdeY3: 215000,
      customerConcentrationMaxPct: 0.15,
      hasCustomerOver10PctContracted: true,
      bankStatementsAvailable: true,
      taxReturnsAvailable: true,
      pnlAvailable: true,
      bankDepositsMatchPnl: true,
      bankDepositVariancePct: 0.01,
      sba7aEligible: "Yes",
      veteransAdvantageApplied: true,
      platformConcentrationMaxPct: 0.12,
      platformName: "LinkedIn",
      paymentProcessorIssue: false,
      sellerIdentityDependencePct: 0,
      ownerDependencePathway: "B",
      keyEmployeeRisk: false,
      keyEmployeeRetentionPlan: false,
      remoteManageable: true,
      operatorProxyIdentified: true,
      communicationAccessConfirmed: true,
      capitalConfirmed: true,
      noCompetingLOI: true,
      isEcommerceSubscription: false,
      ecommerceRecurringRevenuePct: 0,
      governmentRevenuePct: 0,
      arAgingReportAvailable: true,
      customerListAvailable: true,
      hasVagueAddBacks: false,
      maxEarnoutAmount: 0,
      earnoutDurationMonths: 0,
      equityInjectionIsLiquid: true,
      sdePeakLast5Years: 215000,
      monthlyFixedOpCosts: 18000,
      workingCapitalReplenishmentAnnual: 4000,
      capexDeferredMoreThan2Years: false,
      undisclosedPaymentTermination: false,
      referralSourceDependency: false,
      hiddenConcentrationRisk: false,
      pathwayA_GMInPlace: false,
      pathwayA_GMAgreement: false,
      pathwayA_GMPnlHistory: false,
      pathwayB_OwnerReplaceCost: 40000,
      pathwayC_WrittenSOPs: true,
      pathwayC_IndependentExecution30Days: true,
      pathwayC_PostClose90DayPlan: true,
      ownerPerformsSalesAndOpsNoPlan: false,
      ownerControlsPayrollSchedulingNoPlan: false,
      keyEmployeeResponsibleFor20Pct: false,
      keyEmployeeAgreementExists: true,
      keyEmployeeBonusEscrowed: true,
      keyEmployeeWillingToStay: true,
      criticalEmployeeRefusesToStay: false,
      remoteFinancialOversightLess2Hrs: true,
      remoteBlackoutSurvival72Hrs: true,
      ownerMustSignPermitsOrLicense: false,
      ownerValueAddConfirmation: true,
      minimalSoftwareInUse: true,
      manualProcessesIn3CoreWorkflows: true,
      staffTimeReplaceableByAutomation: false,
      recurringModelAvailable: false,
      customerRetentionOver60PctNoContract: true,
      noServiceContractsOffered: false,
      noOnlineBookingOrPortal: true,
      noDigitalMarketingInfrastructure: true,
      laborCostsOver40Pct: false,
      pricingNotRaisedIn2Years: true,
      dealBriefAvailable: true,
      bankDepositSupportAvailable: true,
      orgChartAvailable: true,
      sopsAvailable: true,
      ninetyDayPlanAvailable: true,
      sellerIdentityEvidenceAvailable: true,
      platformConcentrationEvidenceAvailable: true,
      additionalDdDocsAvailable: true,
    }
  }
];

export const INITIAL_OUTREACH_CONTACTS: OutreachContact[] = [
  {
    id: "contact-1",
    name: "Robert Cheney",
    firm: "Sunbelt Business Brokers",
    type: OutreachType.BROKER,
    email: "rcheney@sunbelt.com",
    phone: "(512) 555-0192",
    lastContactDate: "2026-05-29",
    status: OutreachStatus.CIM_REVIEW,
    notes: "Reviewing Apex plumbing. NDA signed on 5/20. CIM received.",
    dealId: "deal-1"
  },
  {
    id: "contact-2",
    name: "Janice Miller",
    firm: "Miller & Associates",
    type: OutreachType.BROKER,
    email: "janice@millerbrokers.com",
    phone: "(312) 555-0348",
    lastContactDate: "2026-06-01",
    status: OutreachStatus.NDA_SIGNED, // fixed typo in standard list status
    notes: "Signed NDA for B2B logistics company in Chicago. Waiting on financials."
  },
  {
    id: "contact-3",
    name: "David Sterling",
    firm: "Sterling Auto Holdings",
    type: OutreachType.DIRECT_CAMPAIGN,
    email: "dsterling@sterlingauto.com",
    phone: "(214) 555-9011",
    lastContactDate: "2026-05-15",
    status: OutreachStatus.CONTACTED,
    notes: "Direct mail lead. Owner is 68, exploring transition plan. Re-evaluate in 30 days."
  },
  {
    id: "contact-4",
    name: "Markus Vance",
    firm: "Acquire.com Network",
    type: OutreachType.COLD_OUTREACH,
    email: "mv@acquisitionguru.co",
    phone: "",
    lastContactDate: "2026-05-30",
    status: OutreachStatus.COLD,
    notes: "Cold outbound on LinkedIn. SaaS owner in logistics space. Interested."
  }
];
